/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 football.gltf 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";

export function Football(props) {
  const { nodes, materials } = useGLTF(
    "/3Dmodels/football_4k.gltf/football.gltf"
  );
  const globeRef = useRef();
  useFrame(({ clock }) => {
    const elapsedTime = clock.getElapsedTime();
    globeRef.current.rotation.y = elapsedTime / 6;
  });
  return (
    <group {...props} dispose={null}>
      <ambientLight intensity={1} />
      <spotLight position={(0, 64, 32)} />

      <mesh
        scale={6}
        ref={globeRef}
        geometry={nodes.football_inflated.geometry}
        material={materials.football}
        position={[0.15, 0.111, 0]}
      />
    </group>
  );
}

useGLTF.preload("/3Dmodels/football_4k.gltf/football.gltf");
